### ISSUE TITLE
I wasn't able to install the plugin, something missing?

### ISSUE THREAD

**Issue by erinjerri** [inkdropapp/inkdrop-math#1]
receive this message upon `ipm install inkdrop-math-master`

`inkdrop/packages ✗
Request for package information failed: missing`

**Comment by craftzdog** [comment]
Please follow the installation instruction here:

https://github.com/inkdropapp/inkdrop-math#install

**Comment by craftzdog** [comment]
> Oh I installed it and I still got the error message that the package was missing.

So the below command introduced the same error?

```
ipm install math
```

I tried but didn't get it.
