### ISSUE TITLE
Incorrect font with v1.2.0

### ISSUE THREAD

**Issue by erning** [inkdropapp/inkdrop-math#11]
It seems that the plugin is still using the old class names of KaTaX style, resulting in incorrect rendering results. 

> Here's the screen shot:
> ![](https://user-images.githubusercontent.com/42628/127102713-5c23146b-95bf-4d08-8839-37c976cda23a.png)

> The expected results should be
> ![](https://github.com/inkdropapp/inkdrop-math/raw/master/docs/images/example-01.png)
> ![](https://github.com/inkdropapp/inkdrop-math/raw/master/docs/images/example-02.png)

According to the [KaTaX's changelog][1], class name `.mathdefault` has been changed to `.mathnormal`.

Currently, I add the following code to `styles.less` as a workaround
```less
.katex .mathnormal {
  font-family: KaTeX_Math;
  font-style: italic;
}
```

[1]: https://github.com/KaTeX/KaTeX/commit/d1c0468ef86f97a3eecdaa9461572fdbbb7088e5#diff-a7d9ebd241057a9c9c16de5bd78ea85ea623f61a13f817e19371b64b96aa0afb

**Comment by craftzdog** [comment]
Good catch! Just published v1.2.1 🎉
