### ISSUE TITLE
Using '_' after symbol, end up italic

### ISSUE THREAD

**Issue by moba1** [inkdropapp/inkdrop-math#2]
In math mode, using `_`after character except for `[a-zA-Z0-9]`, `:`, `)`, `>`, `}`, and etc., inkdrop editor end up printing subsequent characters in italic.

**Comment by craftzdog** [comment]
`$$` block doesn't support syntax highlighting.
Please use `math` code block to avoid the problem.

**Comment by moba1** [comment]
Thanks!
