### ISSUE TITLE
Inline math not functional

### ISSUE THREAD

**Issue by nicpitsch** [inkdropapp/inkdrop-math#20]
To me the inline math example from readme is not functional in Inkdrop:
`Inline math: $\int_0^\infty \frac{x^3}{e^x-1}\,dx = \frac{\pi^4}{15}$`

**Comment by craftzdog** [comment]
What's your Inkdrop and plugin versions?

**Comment by nicpitsch** [comment]
Sorry for omitting fundamental infos:

Versions: 

* Inkdrop 5.6.0 beta.0 on Windows 11.
* inkdrop-math v1.3.0.

Plugins, respectively subfolders in *C:\Users\[username]\AppData\Roaming\inkdrop\packages* folder (always the latest versions:):

* admonition
* autoupdate-list-numbers
* code-title
* focus-button
* footnotes
* goldgreen-dark-ui
* highlight-text
* horizon-dark-preview
* horizon-dark-syntax
* horizon-dark-ui
* markdown-emoji
* material-dark-mod-syntax
* material-ocean-preview
* material-ocean-syntax
* material-ocean-ui
* math
* mermaid
* nord-preview
* nord-syntax
* nord-ui
* octopus-dark-preview
* octopus-dark-syntax
* octopus-dark-ui
* open-in-external-editor
* paste-as-markdown
* paste-url
* plastic-syntax
* pomodoro-edit
* sequence-diagrams
* sharp-fourth-preview
* sidetoc
* simple-note-list
* stylized-fantasy-syntax-theme
* table-editor
* toc
* tray
* vibrant-dark-ui
* web-clipper

Edit: by far not all are installed in Inkdrop.

**Comment by nicpitsch** [comment]
Now inline math is functional. What I have done so far:

* Disable all the plugins despite math. ➜ inline math is functional.
* Re-enabled one after the oter plugins. ➜ inline math stays functional, also after restarting Inkdrop.

On Inkdrop restart there are now messages:

![grafik](https://github.com/inkdropapp/inkdrop-math/assets/1652835/0ae45a59-4cd6-482e-9132-e187a91f966d)

I will investigate further, some where it must be some incompatibility regarding another plugin, what do you think?

I propose you don't waste your time with this, I will let know here as soon as I might have further information.

**Comment by craftzdog** [comment]
As the error messages say, these plugins don't support v5.6.0.
That's because it has [a new Markdown renderer](https://forum.inkdrop.app/t/inkdrop-desktop-v5-6-0-beta-0/4102).
`autoupdate-list-numbers` or `footnotes` is no longer necessary as it is supported by default now.
`admonition` is no longer maintained and should be removed from the registry.

Can you please report it to the highlight-text plugin author?

**Comment by nicpitsch** [comment]
Thanks for the information.  After disabling and re-enabling the plugins as explained above, math stay's functional. I have removed the incompatible plugins and others I didn't need.
