### ISSUE TITLE
Failed to load in Ubuntu 18.04

### ISSUE THREAD

**Issue by Kurt-Pan** [inkdropapp/inkdrop-math#3]
![image](https://user-images.githubusercontent.com/41199373/47266899-272ac280-d56f-11e8-9cc9-86a8a0ef84c5.png)

**Comment by craftzdog** [comment]
Can you please report a stack trace?
You can check it from `Developer -> Toggle Developer Tools`.

**Comment by craftzdog** [comment]
No response. Closing.
