### ISSUE TITLE
How to input math fomula with multiple lines?

### ISSUE THREAD

**Issue by gogdizzy** [inkdropapp/inkdrop-math#4]
$$
s=(p,v,a) \\
u=j
$$

will got error:
KaTeX parse error: Expected 'EOF', got '\\' at position 10: s=(p,v,a)\̲\̲
u=j

Thank you

**Comment by craftzdog** [comment]
Hi @gogdizzy,

Use `\begin{aligned}`:

```math
\begin{aligned}
\text{A + B = C} \\
\text{C - B = A}
\end{aligned}
```
