### ISSUE TITLE
Fails to render a number of symbols supported by KaTeX

### ISSUE THREAD

**Issue by tonyonodi** [inkdropapp/inkdrop-math#5]
I've noticed that some of the functionality that KaTeX claims to have is missing from this plugin. I've not tested it exhaustively, but `\N`, `\natums`, `\\`, `\newline` and `\R` all claim to be supported in the [KaTeX documentation](https://katex.org/docs/supported.html), but don't work in the plugin.

I had a look at the `package.json` of this project and it seems that it has `react-katex 2.0.2` as a dependency, which in turn has `katex 0.10.0` as a dependency ([relevant package.json](https://github.com/MatejBransky/react-katex/blob/04971481970b31ecb7931c08f16abbbe4f1fb807/package.json)), while the most recent version of katex is `0.12.0`. I don't know if this is the cause of these functions not being supported, but it seems like a good place to start.

The most recent version of `react-katex` will accept `katex >= 0.9.0` as a peer dependency.

I would look into this issue more myself, but I don't have the time to set up a dev environment and understand inkdrop plugins better right now, so for now I'm just filing this issue :)

**Comment by craftzdog** [comment]
Thank you for reporting it.
Okay, let's update `react-katex`.

**Comment by craftzdog** [comment]
math@1.1.0 is landed🎉
I confirmed that `\N`, `\\`, `\newline` and `\R` now work fine.

**Comment by tonyonodi** [comment]
Amazing, thank you! And thanks for Inkdrop, I'm a new user and really impressed with it :)
